# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f64ecc5c214f8224c8efc6e0ffeb331d"
application_url = "https://route-farmer-cuba-finland.trycloudflare.com"
embedded = true
name = "wishlist"
handle = "wishlist-659"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://route-farmer-cuba-finland.trycloudflare.com/auth/callback",
  "https://route-farmer-cuba-finland.trycloudflare.com/auth/shopify/callback",
  "https://route-farmer-cuba-finland.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "tahsin-app-dev.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
